runtime: ruby27
entrypoint: bundle exec rails server -e production -p $PORT
service: kokenwiki
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_idle_instances: 0
  max_idle_instances: 1
