version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./init-mysql-docker-compose.sql:/docker-entrypoint-initdb.d/init.sql
      - mysqlsockdir:/var/run/mysqld
    network_mode: none
  rails:
    build: .
    volumes:
      - mysqlsockdir:/var/run/mysqld
    ports:
      - "3000:3000"
    network_mode: bridge
    depends_on:
      - mysql
volumes:
  mysqlsockdir:

